### ISSUE TITLE
Add Todo Item

### ISSUE THREAD

**Issue by GeorgeCiesinski** [GeorgeCiesinski/todo-list#10]
The list element should include a button to add a new todo item.

- [x] Add todo button
- [x] Creates a new todo item
- [x] Creates a new todo element
- [x] Changes focus to todo name

**Comment by GeorgeCiesinski** [comment]
Completed in commit [f02eaab](https://github.com/GeorgeCiesinski/todo-list/commit/f02eaab9c6bc950de6bb6d9004ea583cd8c3f50f)
