### ISSUE TITLE
TODO functionality

### ISSUE THREAD

**Issue by GeorgeCiesinski** [GeorgeCiesinski/todo-list#7]
This issue tracks the planned features of the TODO items. 

# TODO main inputs

- [x] Checkbox
- [x] Checkbox saves
- [x] Name
- [x] Name saves
- [x] Priority
- [x] Priority saves
- [x] Due
- [x] Due saves
- [x] Due checks if before created
- [x] Notes
- [x] Notes saves
- [x] Created
- [x] Created saves
- [x] Created checks if after due date

# Adding

- [x] Add Todo Button
- [x] Add Todo Button changes focus
- [x] Add Todo Item
- [x] Add Todo Item saves

# Deleting

- [x] Delete Todo Button
- [x] Delete Todo Item
- [x] Delete Todo Item saves
- [x] Update indices

# Todo inner inputs

Tracks the checklist behavior and planned features.

- [x] Inner checkbox
- [x] Inner checkbox saves
- [x] Inner name
- [x] Inner name saves
- [x] Add checklist item
- [x] Delete checklist item

**Comment by GeorgeCiesinski** [comment]
Completed in commit [72cb70](https://github.com/GeorgeCiesinski/todo-list/commit/72cb709ef12dbe05bb33e383b4fe0add83ed14c9)
