### ISSUE TITLE
Add Checklist Item

### ISSUE THREAD

**Issue by GeorgeCiesinski** [GeorgeCiesinski/todo-list#9]
The todo checklist section needs several features. Currently, if there is no checklist, the section is missing from the page. Instead, there should at least be a checklist section with an "add" button if no items exist. The button should remain even if there are checklist items.

- [x] Persistent Checklist Section
- [x] Add Checklist Button
- [x] Add Checklist Button should add a new checklist item and focus on the name
- [x] Add Checklist Logic

**Comment by GeorgeCiesinski** [comment]
When button is clicked, the steps should be taken in order:
1) Create new item in array, returns new length
- [x] Create item

2) Use returned value to get index and item number, create element
- [x] Create element

3) Change focus to new element name
- [x] Change focus

**Comment by GeorgeCiesinski** [comment]
Issue complete in commit [123ef12](https://github.com/GeorgeCiesinski/todo-list/commit/123ef123ce412c9d2d79bfc91de3ad992d57d203)
